
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-Tides-Controller","number":60,"title":"Add Tides Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/60"},{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-ZipCode-Controller","number":59,"title":"Add Zipcode Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/59"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"Evan-Location-Controller","number":58,"title":"Evan location controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/58"},{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"Julia-Joke-Controller","number":57,"title":"Added joke controller and test","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/57"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-PublicHoliday-Controller","number":54,"title":"Kai public holiday controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/54"}]
