
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-ZipCode","number":50,"title":"Kelly zip code","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/50"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"Kriteen-University","number":48,"title":"Add University Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/48"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-PublicHoliday","number":47,"title":"Add PublicHoliday Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/47"}]
