
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"Julia-Joke","number":55,"title":"Add Joke Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/55"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-PublicHoliday-Controller","number":54,"title":"Kai public holiday controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/54"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-Tides","number":53,"title":"Update Code","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/53"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"Kriteen-HomeController","number":51,"title":"Added HomeController","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-2/pull/51"}]
